version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: app
    volumes:
      - ./app/src/api:/go/src/api
    expose:
      - "8080"

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
